# Generated by Django 4.0.8 on 2023-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(default='https://psediting.websites.co.in/obaju-turquoise/img/product-placeholder.png'),
        ),
    ]
